### ISSUE TITLE
Rock RMS

### ISSUE THREAD

**Issue by ssddanbrown** [ssddanbrown/Open-Source-Confusers#2]
https://github.com/SparkDevNetwork/Rock/issues/5068

Need to validate this project has "reasonable following, popularity or visibility" before adding.

**Comment by elliotwutingfeng** [comment]
Similarweb [global rank](https://www.similarweb.com/website/rockrms.com) of https://rockrms.com is 945,092.

**Comment by ssddanbrown** [comment]
Added in ee6709444dd08e7922ec0bb126ef441a3ed9d6e1.

@elliotwutingfeng Thanks, hard to put a global site rank into relative terms to be honest.

I did see they have over [80 reviews on Capterra](https://www.capterra.com/p/141654/Rock-RMS/) so look fairly well established.
